services:
  backend:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: power_sensor
      MYSQL_USER: power_user
      MYSQL_PASSWORD: power_password
      TZ: Asia/Bangkok   # ✅ เพิ่มบรรทัดนี้
    volumes:
      - db_data:/var/lib/mysql
      - ./power_sensor.sql:/docker-entrypoint-initdb.d/power_sensor.sql # Mount ไฟล์ SQL โดยตรง
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    restart: always
volumes:
  db_data:
